---
dependencies:
  - name: rabbitmq
    version: 6.25.4
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install
  - name: postgresql
    version: 8.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install
  - name: memcached
    version: 4.2.16
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.install
